//BIODATA
#include<iostream>
using namespace std;
int main()
{ system ("cls");
string name , surname,adress, fname , mname;
int age;
cout<<"enter your name, age , adress , fathers name, mothers name :";
cin>>name >> surname;
cin>> age;
cin>> adress;
cin >> fname >> surname;
cin >> mname >> surname ;
cout<< " MY NAME IS "<<name<< " " << surname;
cout<<"\nI AM "<<age << " years old.";
cout<<"\nI LIVE IN "<<adress;
cout<<"\n MY FATHERS NAME IS "<<fname<< " "<< surname;
cout<<"\n MY MOTHERS NAME IS "<<mname<< " "<< surname;

return 0;}
